#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: '/VerdantAges' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

#
# Title
#
title: VerdantAges
title_separator: '|'
subtitle: 'An immersive medieval-inspired minecraft modpack focused on exploration of the natural world.'

description: >- # this means to ignore newlines until 'baseurl:'
  Documentation for the VerdantAges Minecraft modpack, which provides an in immersive medieval-inspired minecraft experience focused on exploration of the natural world.

#
# Author
#
name: 'Lacey-Anne Sanderson (MossbornHedgehog)'
github_username: MossbornHedgehog
repository: 'MossbornHedgehog/VerdantAges'

#
# Theme Settings
#
minimal_mistakes_skin: 'dark' # 'air', 'aqua', 'contrast', 'dark', 'dirt', 'neon', 'mint', 'plum', 'sunrise'
include: ["_pages"]

#
# Build settings
#
remote_theme: 'mmistakes/minimal-mistakes@4.27.3'
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal 'default list'.
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
